### ISSUE TITLE
CodeCatalystに開発環境を作るには

### ISSUE THREAD

**Issue by gosaaan1** [gosaaan1/hokulea-garage#24]
個々のPCに開発環境を構築する場合、ハードウェア性能やOSの違いなどによりどうしても”ばらつき”が起こりやすく、セットアップがスムーズにいかない、マシンが重くて使えないというケースがよくあると思います。また複数ある開発環境それぞれをクリーンに保ちたい（バージョン違いの複数の環境を持っておきたい）というニーズもあると思います。

CodeCatalystには [Devfile](https://devfile.io/) を使って、AWS上に簡単にクラウドの開発環境を構築する機能があり、これを使うと面倒な手順書づくりや、開発環境構築に必要なプラットフォーム依存のフォローから開放されます。

**Comment by gosaaan1** [comment]
![Screenshot 2024-03-24 10 37 30](https://github.com/gosaaan1/hokulea-garage/assets/123862848/9eccc567-cd5d-43a4-a610-6d70b0cbeec0)

[開発環境の設定 (CodeCatalyst)](https://docs.aws.amazon.com/ja_jp/codecatalyst/latest/userguide/devenvironment-devfile.html)より

> ルートに devfile を含まないソースリポジトリを使用して開発環境を作成する場合、またはソースリポジトリなしで開発環境を作成する場合、デフォルトのユニバーサル devfile がソースリポジトリに自動的に適用されます。

ちなみに、以下のような内容のdevfile.yamlが生成されます。

```
schemaVersion: 2.0.0
metadata:
  name: aws-universal
  version: 1.0.1
  displayName: AWS Universal
  description: Stack with AWS Universal Tooling
  tags: ["aws", "al2"]
  projectType: "aws"
components:
  - name: aws-runtime
    container:
      image: [public.ecr.aws/aws-mde/universal-image:latest](http://public.ecr.aws/aws-mde/universal-image:latest)
      mountSources: true
      volumeMounts:
        - name: docker-store
          path: /var/lib/docker
  - name: docker-store
    volume:
      size: 16Gi
```
